### ISSUE TITLE
[Feature Request] Migrate `trust` to `float` instead of `string`

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/thenewboston-node#168]
Currently, the `trust` field used for various server nodes on the network (ex: https://thenewboston.com/bank-api/accounts) is serialized as a `string`.  However, this is terrible for using within basically all programming languages as you need to parse the text into a float.  It would be a lot easier if it was just serialized as a float.

**Comment by dmugtasimov** [comment]
@sno2 `trust` is not implemented in the node API yet, but I will consider your request. Meanwhile here is a good explanation why string could be a better option: https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html

**Comment by sno2** [comment]
> Meanwhile here is a good explanation why string could be a better option: https://husobee.github.io/money/float/2016/09/23/never-use-floats-for-currency.html

I don't think that article states that strings could be better.  If you are going to be doing arithmetic then you still need to parse it into a float then do something which will still result in these bit bugs.  Therefore, we're actually using floats right now as we have 2 decimal pts.  I think the argument that article was trying to make was to just use ints over floats to avoid the calculation inconsistencies across programming languages.

**Comment by dmugtasimov** [comment]
@sno2 There are fixed point decimal type. In Python we have https://docs.python.org/3/library/decimal.html , in databases it is Numeric and Decimal. Usually, there two options to avoid issue with float calculation errors: use integers and switch to minor units (then multiply/divide on serialization/deserialization) or use more advanced datatypes like decimals (unfortunately they are not supported by JSON and therefore we have to use strings, but it is fine, since there is another example of such unsupported datatype: datetime).

**Comment by buckyroberts** [comment]
No trust field in the beta nodes. Closing.
